# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: matrix_computations.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='matrix_computations.proto',
  package='matrix_computations',
  syntax='proto3',
  serialized_options=b'P\001\242\002\003HLW',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19matrix_computations.proto\x12\x13matrix_computations\"8\n\x12\x43omputationRequest\x12\x10\n\x08matrix_1\x18\x01 \x01(\t\x12\x10\n\x08matrix_2\x18\x02 \x01(\t\"#\n\x11\x43omputationResult\x12\x0e\n\x06matrix\x18\x01 \x01(\t2\xcf\x01\n\x08\x43omputer\x12\x63\n\x0emultiply_block\x12\'.matrix_computations.ComputationRequest\x1a&.matrix_computations.ComputationResult\"\x00\x12^\n\tadd_block\x12\'.matrix_computations.ComputationRequest\x1a&.matrix_computations.ComputationResult\"\x00\x42\x08P\x01\xa2\x02\x03HLWb\x06proto3'
)




_COMPUTATIONREQUEST = _descriptor.Descriptor(
  name='ComputationRequest',
  full_name='matrix_computations.ComputationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='matrix_1', full_name='matrix_computations.ComputationRequest.matrix_1', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='matrix_2', full_name='matrix_computations.ComputationRequest.matrix_2', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=106,
)


_COMPUTATIONRESULT = _descriptor.Descriptor(
  name='ComputationResult',
  full_name='matrix_computations.ComputationResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='matrix', full_name='matrix_computations.ComputationResult.matrix', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=143,
)

DESCRIPTOR.message_types_by_name['ComputationRequest'] = _COMPUTATIONREQUEST
DESCRIPTOR.message_types_by_name['ComputationResult'] = _COMPUTATIONRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ComputationRequest = _reflection.GeneratedProtocolMessageType('ComputationRequest', (_message.Message,), {
  'DESCRIPTOR' : _COMPUTATIONREQUEST,
  '__module__' : 'matrix_computations_pb2'
  # @@protoc_insertion_point(class_scope:matrix_computations.ComputationRequest)
  })
_sym_db.RegisterMessage(ComputationRequest)

ComputationResult = _reflection.GeneratedProtocolMessageType('ComputationResult', (_message.Message,), {
  'DESCRIPTOR' : _COMPUTATIONRESULT,
  '__module__' : 'matrix_computations_pb2'
  # @@protoc_insertion_point(class_scope:matrix_computations.ComputationResult)
  })
_sym_db.RegisterMessage(ComputationResult)


DESCRIPTOR._options = None

_COMPUTER = _descriptor.ServiceDescriptor(
  name='Computer',
  full_name='matrix_computations.Computer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=146,
  serialized_end=353,
  methods=[
  _descriptor.MethodDescriptor(
    name='multiply_block',
    full_name='matrix_computations.Computer.multiply_block',
    index=0,
    containing_service=None,
    input_type=_COMPUTATIONREQUEST,
    output_type=_COMPUTATIONRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='add_block',
    full_name='matrix_computations.Computer.add_block',
    index=1,
    containing_service=None,
    input_type=_COMPUTATIONREQUEST,
    output_type=_COMPUTATIONRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMPUTER)

DESCRIPTOR.services_by_name['Computer'] = _COMPUTER

# @@protoc_insertion_point(module_scope)
