# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app import matrix_computations_pb2 as matrix__computations__pb2


class ComputerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.multiply_block = channel.unary_unary(
                '/matrix_computations.Computer/multiply_block',
                request_serializer=matrix__computations__pb2.ComputationRequest.SerializeToString,
                response_deserializer=matrix__computations__pb2.ComputationResult.FromString,
                )
        self.add_block = channel.unary_unary(
                '/matrix_computations.Computer/add_block',
                request_serializer=matrix__computations__pb2.ComputationRequest.SerializeToString,
                response_deserializer=matrix__computations__pb2.ComputationResult.FromString,
                )


class ComputerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def multiply_block(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def add_block(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComputerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'multiply_block': grpc.unary_unary_rpc_method_handler(
                    servicer.multiply_block,
                    request_deserializer=matrix__computations__pb2.ComputationRequest.FromString,
                    response_serializer=matrix__computations__pb2.ComputationResult.SerializeToString,
            ),
            'add_block': grpc.unary_unary_rpc_method_handler(
                    servicer.add_block,
                    request_deserializer=matrix__computations__pb2.ComputationRequest.FromString,
                    response_serializer=matrix__computations__pb2.ComputationResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'matrix_computations.Computer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Computer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def multiply_block(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/matrix_computations.Computer/multiply_block',
            matrix__computations__pb2.ComputationRequest.SerializeToString,
            matrix__computations__pb2.ComputationResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def add_block(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/matrix_computations.Computer/add_block',
            matrix__computations__pb2.ComputationRequest.SerializeToString,
            matrix__computations__pb2.ComputationResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
